apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mm-service
  name: mm-service
  labels:
    app: mm-service
spec:
  selector:
    matchLabels:
      app: mm-service
  template:
    metadata:
      labels:
        app: mm-service
        name: mm-service
    spec:
      containers:
        - name: mm-service
          image: mahendraintelops/mm-project/mm-service
          imagePullPolicy: Always
       
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        