apiVersion: v1
kind: Service
metadata:
  namespace: mm-service
  labels:
    app: mm-service
  name: mm-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: mm-service
  type: ClusterIP
